<?xml version='1.0'?>

<!-- Source:https://github.com/qboticslabs/mastering_ros/tree/master/chapter_2_codes/mastering_ros_robot_description_pkg -->

<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find my_robot)/urdf/my_robot.gazebo" />
  <!--xacro:include filename="$(find my_robot)/urdf/wheel.xacro" /-->

<!-- Defining the colors used in this robot -->
  <material name="Black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <material name="Red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <material name="White">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>

  <material name="Blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>

  <material name="Orange">
    <color rgba="0.98 0.4 0.02 1.0"/>
  </material>

  <material name="Indigo" >
    <color rgba="0.22 0.01 0.51 1.0" />
  </material>

  <material name="DarkGrey" >
    <color rgba="0.22 0.22 0.22 1.0" />
  </material>

  <!-- PROPERTY LIST -->
  <!--All units in m-kg-s-radians unit system -->
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="M_PI_2" value="1.570796327" />
  <xacro:property name="DEG_TO_RAD" value="0.017453293" />

  <!-- Main body radius and height -->
  <!-- Main Body Cylinder base   -->
  <xacro:property name="base_height" value="0.05" /> 
  <xacro:property name="base_radius" value="0.15" /> 
  <xacro:property name="base_mass" value="10" /> <!-- in kg-->

  <!-- caster wheel radius and height -->
  <!-- caster wheel mass -->
  <xacro:property name="caster_f_height" value="0.04" /> 
  <xacro:property name="caster_f_radius" value="0.0199" /> 
  <xacro:property name="caster_f_mass" value="0.5" /> <!-- in kg-->

  <!-- caster wheel radius and height -->
  <!-- caster wheel mass -->
  <xacro:property name="caster_b_height" value="0.04" /> 
  <xacro:property name="caster_b_radius" value="0.0199" /> 
  <xacro:property name="caster_b_mass" value="0.5" /> <!-- in kg-->

  <!-- Wheels -->
  <xacro:property name="wheel_radius" value="0.04" /> 
  <xacro:property name="wheel_height" value="0.02" />
  <xacro:property name="wheel_mass" value="2.5" /> <!-- in kg-->
  <xacro:property name="base_x_origin_to_wheel_origin" value="0.25" />
  <xacro:property name="base_y_origin_to_wheel_origin" value="0.15" />
  <xacro:property name="base_z_origin_to_wheel_origin" value="0.0" />

  <!-- Hokuyo Laser scanner -->
  <xacro:property name="hokuyo_size" value="0.08" />

  <!-- Camera -->
  <xacro:property name="camera_size" value="0.05" />

  <!-- Macro for calculating inertia of cylinder -->
  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
              iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
              izz="${m*r*r/2}" /> 
  </xacro:macro>

  <!-- BASE-FOOTPRINT -->
  <!-- robot_footprint is a fictitious link(frame) that is on the ground right below chassis origin -->
  <link name="robot_footprint">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="0.001 0.001 0.001" />
        </geometry>
    </visual>
  </link>

  <gazebo reference="robot_footprint">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <joint name="robot_footprint_joint" type="fixed">
    <origin xyz="0 0 ${wheel_radius - base_z_origin_to_wheel_origin}" rpy="0 0 0" />
    <parent link="robot_footprint"/>
    <child link="chassis" />
  </joint>

  <!-- BASE-LINK -->
  <!--Actual body/chassis of the robot-->
  <link name="chassis">
    <pose>0 0 0 0 0 0</pose>
    <inertial>
      <mass value="${base_mass}" />
      <origin xyz="0 0 0" />
      <!--The 3x3 rotational inertia matrix. -->
        <cylinder_inertia  m="${base_mass}" r="${base_radius}" h="${base_height}" />
    </inertial>    
    <visual name='chassis_visual'>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
          <cylinder length="${base_height}" radius="${base_radius}" />
      </geometry>
      <material name="Indigo" />
    </visual>  
    <collision name='chassis_collision'>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
          <cylinder length="${base_height}" radius="${base_radius}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="chassis">
    <material>Gazebo/Indigo</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <!--Caster front  -->
  <link name="caster_front_link">
    <visual name='front_caster_visual'>
      <origin xyz="0 0.02 0" rpy="${M_PI/2} 0 0" />
      <geometry>
	      <sphere radius="${caster_f_radius}" />
      </geometry>
      <material name="Black" />
    </visual>  
    <collision name='front_caster_collision'>
      <geometry>
	      <sphere radius="${caster_f_radius}" />
      </geometry>
      <origin xyz="0 0.02 0" rpy="${M_PI/2} 0 0" />
      <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
  </link>

 <joint name="caster_front_joint" type="fixed">
      <parent link="chassis"/>
      <child link="caster_front_link"/>
      <origin xyz="0.115 0.0 0.00" rpy="${-M_PI/2} 0 0"/>
  </joint>

  <gazebo reference="caster_front_link">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

   <!--Caster back  -->
  <link name="caster_back_link">
    <visual name='back_caster_visual'>
      <origin xyz="0.02 0.02 0" rpy="${M_PI/2} 0 0" /> 
      <geometry>
	      <sphere radius="${caster_b_radius}" />
      </geometry>
      <material name="Black" />
    </visual>
    <collision name='back_caster_collision'>
      <geometry>
		    <sphere radius="${caster_b_radius}" />
      </geometry>
      <origin xyz="0.02 0.02 0" rpy="${M_PI/2} 0 0" />
      <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    </link>

  <joint name="caster_back_joint" type="fixed">
    <parent link="chassis"/>
    <child link="caster_back_link"/>
    <origin xyz="-0.135 0.0 0.00" rpy="${-M_PI/2} 0 0"/>
  </joint>

  <gazebo reference="caster_back_link">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <!-- Wheel Definitions -->

	<joint type="continuous" name="left_wheel_hinge">
    <origin xyz="0 ${base_y_origin_to_wheel_origin} 0" rpy="0 0 0"/>
    <child link="left_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>
  
  <joint type="continuous" name="right_wheel_hinge">
    <origin xyz="0 -${base_y_origin_to_wheel_origin} 0" rpy="0 0 0"/>
    <child link="right_wheel"/>
    <parent link="chassis"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <!-- Transmission is important to link the joints and the controller -->
  <transmission name="left_wheel_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_wheel_hinge" />
    <actuator name="left_wheel_joint_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="right_wheel_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_wheel_hinge" />
    <actuator name="right_wheel_joint_motor">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <link name="left_wheel">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0.0 0 0" rpy="0 1.5707 1.5707"/>
      <cylinder_inertia  m="${wheel_mass}" r="${wheel_radius}" h="${wheel_height}"/>
    </inertial>
    <collision name='left_wheel_collision'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/> 
      <geometry>
        <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
      </geometry>
    </collision>   
    <visual name='left_wheel_visual'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/> 
      <geometry>
        <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
      </geometry>
      <material name="DarkGrey"/>
    </visual>   
  </link>

  <gazebo reference="left_wheel">
    <material>Gazebo/DarkGrey</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <link name="right_wheel">
    <inertial>
      <mass value="${wheel_mass}"/>
      <origin xyz="0.0 0 0" rpy="0 1.5707 1.5707"/>
      <cylinder_inertia  m="${wheel_mass}" r="${wheel_radius}" h="${wheel_height}"/>
    </inertial>
    <collision name='right_wheel_collision'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/> 
      <geometry>
        <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
      </geometry>
    </collision>   
    <visual name='right_wheel_visual'>
      <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/> 
      <geometry>
        <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
      </geometry>
      <material name="DarkGrey"/>
    </visual>   
  </link>

  <gazebo reference="right_wheel">
    <material>Gazebo/DarkGrey</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <!-- SENSORS -->
  
  <!-- hokuyo -->
  <link name="hokuyo">
    <inertial>
      <mass value="1e-5"/>
      <origin xyz="0.0 0 0" rpy="0 0 0"/>
      <inertia 
      	ixx="1e-6" ixy="0.0" ixz="0.0"
      	iyy="1e-6" iyz="0.0" izz="1e-6"
      />
    </inertial>
    <collision name='hokuyo_collision'>
      <origin xyz="0 0 0" rpy="0 0 0"/> 
      <geometry>
        <!--box size="${hokuyo_size} ${hokuyo_size} ${hokuyo_size}"/-->
        <mesh filename="package://my_robot/meshes/hokuyo.dae"/>
      </geometry>
    </collision>
    <visual name='hokuyo_visual'>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <!--box size="${hokuyo_size} ${hokuyo_size} ${hokuyo_size}"/-->
        <mesh filename="package://my_robot/meshes/hokuyo.dae"/>
      </geometry>
      <material name="Blue" />
    </visual>
  </link>

  <joint name="hokuyo_joint" type="fixed">
    <origin xyz="${base_radius/2} 0 ${base_height}" rpy="0 0 0" />
    <parent link="chassis"/>
    <child link="hokuyo" />
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint>

  <gazebo reference="hokuyo">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- camera -->
  <link name= "camera">
  	<inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia 
      	ixx="1e-6" ixy="0.0" ixz="0.0"
      	iyy="1e-6" iyz="0.0" izz="1e-6"
      />
    </inertial>
    <collision name='camera_collision'>
      <origin xyz="0 0 0" rpy="0 0 0"/> 
      <geometry>
        <box size="${camera_size} ${camera_size} ${camera_size}"/>
      </geometry>
    </collision> 
    <visual name='camera_visual'>
      <origin xyz="0 0 0" rpy="0 0 0"/> 
      <geometry>
        <box size="${camera_size} ${camera_size} ${camera_size}"/>
      </geometry>
      <material name="Orange" />
    </visual>   
  </link>

  <joint name="camera_joint" type="fixed">
    <origin xyz="${base_radius + camera_size/2} 0 ${base_height/2}" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="camera"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
    <limit effort="10000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
  </joint>

  <link name="camera_link_optical">
  </link>

  <joint name="camera_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}"/>
    <parent link="camera"/>
    <child link="camera_link_optical"/>
  </joint>
  <!--joint name="camera_joint" type="fixed">
    <origin xyz="${base_radius + camera_size/2} 0 ${base_height/2}" rpy="0 0 0"/>
    <parent link="chassis"/>
    <child link="camera" />
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint-->

  <!--gazebo reference="camera">
    <material>Gazebo/Orange</material>
  </gazebo-->

  <gazebo reference="camera">
    <material>Gazebo/Orange</material>
  </gazebo>

</robot>
